name = "blog"
type = "webpack"
usage_model = 'unbound'
account_id = "0c25235045ad6791c9b6c99531934bc2"
compatibility_flags = []
workers_dev = true
site = {bucket = "./public"}
compatibility_date = "2022-11-10"
