name: Deploy

on: [push, repository_dispatch]

jobs:
  build:
    name: Deploy Hexo Public To Pages
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
        with:
          submodules: true # Checkout private submodules(themes or something else).

      - name: Install Dependencies
        run: |
          npm install hexo-cli -g
          npm install

      - name: hexo generate
        run: |
          hexo clean
          hexo g

      # 推送到仓库 from https://github.com/peaceiris/actions-gh-pages
      - name: Deploy hexo to Github pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          external_repository: aucub/aucub.github.io
          publish_branch: master
          publish_dir: ./public
          full_commit_message: ${{ github.event.head_commit.message }}
          exclude_assets: ""
